export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const SHOW_POPUP = 'APP/SHOW_POPUP';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SET_VIEW = 'APP/SET_VIEW';



export const LOGIN_USER = 'USER/LOGIN_USER';
export const LOGOUT_USER = 'USER/LOGOUT_USER';

export const SET_FILES = 'FILES/SET_FILES';
export const SET_CURRENT_DIR = 'FILES/SET_CURRENT_DIR';
export const ADD_FILE = 'FILES/ADD_FILE';
export const DELETE_FILE = 'FILES/DELETE_FILE';
export const PUSH_TO_STACK = 'FILES/PUSH_TO_STACK';
export const POP_FROM_STACK = 'FILES/POP_FROM_STACK';

export const SHOW_UPLOADER = 'UPLOADER/SHOW_UPLOADER';
export const HIDE_UPLOADER = 'UPLOADER/HIDE_UPLOADER';
export const ADD_UPLOAD_FILE = 'UPLOADER/ADD_UPLOAD_FILE';
export const REMOVE_UPLOAD_FILE = 'UPLOADER/REMOVE_UPLOAD_FILE';
export const CHANGE_UPLOAD_FILE = 'UPLOADER/CHANGE_UPLOAD_FILE';
